### PR TITLE
Create VGG19.draft.md

### PR DESCRIPTION
**Pull request by sezan92**
## Objective

This PR adds an initial draft for demonstration so that others can follow the same procedure.

After merging this PR, we will open a PR to the original base repository.

### CODE REVIEW

**Comment by albertkao227** [comment]
Hi just confirming, is this for demonstration only so there is no content in the markdown?

**Comment by sezan92** [comment]
@albertkao227 this is demo for @ShamieCC . when she gets the idea i will go with real prs

**Comment by ShamieCC** [comment]
Thank you @sezan92

**Review by ShamieCC — COMMENTED** [review]
[summary.md](https://github.com/sezan92/computer-vision-course/files/13194800/summary.md)
I know this is just an example for me, thank you for creating this just for me to see the steps. I have seen that i can either comment, approve or request changes before submitting a review. I have also attached a file, is this how I should do it?

**Pull request merged**
